/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.list;

import controllers.KhoaCtrl;
import controllers.NganhCtrl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.NganhModel;
import utils.DialogHelper;

/**
 *
 * @author ACER
 */
public class DSNganh extends javax.swing.JFrame {

    /**
     * Creates new form DSNganh
     */
    DefaultTableModel tableModel;
    List<NganhModel> dsNganh;
    ArrayList<String> dsMaKhoa;
    int countMaKhoa;

    public DSNganh() {
        initComponents();
        tableModel = (DefaultTableModel) tblDSNganh.getModel();

        hienThiDSKhoa();
        hienThiDSNganh();
    }

    private void hienThiDSKhoa() {
        try {
            dsMaKhoa = NganhCtrl.timTatCaMaKhoa();
            countMaKhoa = dsMaKhoa.size();
            cmbMaKhoa.removeAllItems();
            for (String item : dsMaKhoa) {
                cmbMaKhoa.addItem(item);
            }
            cmbMaKhoa.addItem("---Mã khoa---");
            cmbMaKhoa.setSelectedItem("---Mã khoa---");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhoaCtrl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hienThiDSNganh() {
        try {
            dsNganh = NganhCtrl.timTatCaNganh();

            tableModel.setRowCount(0);
            dsNganh.forEach(nganh -> {
                String trangThai = "";
                if (nganh.getTrangThaiHienThi() == 0) {
                    trangThai = "Ẩn";
                } else {
                    trangThai = "Hiển thị";
                }

                tableModel.addRow(new Object[]{
                    nganh.getMaNganh(), nganh.getTenNganh(), nganh.getMaKhoa(), trangThai});
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhoaCtrl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void lamMoi() {
        txtMaNganh.setText("");
        txtTenNganh.setText("");
        cmbTrangThaiHienThi.setSelectedIndex(1);
        txtMaNganh.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChiTiet = new javax.swing.JPanel();
        lblMaNganh = new javax.swing.JLabel();
        lblTenNganh = new javax.swing.JLabel();
        lblMaKhoa = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        txtMaNganh = new javax.swing.JTextField();
        txtTenNganh = new javax.swing.JTextField();
        cmbTrangThaiHienThi = new javax.swing.JComboBox<>();
        cmbMaKhoa = new javax.swing.JComboBox<>();
        pnlNutLenh = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        pnlDSNganh = new javax.swing.JPanel();
        pnlTieuDe = new javax.swing.JPanel();
        lblDanhSachKhoa = new javax.swing.JLabel();
        scrDSNganh = new javax.swing.JScrollPane();
        tblDSNganh = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách ngành");
        setPreferredSize(new java.awt.Dimension(730, 480));

        pnlChiTiet.setBackground(new java.awt.Color(255, 255, 255));

        lblMaNganh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNganh.setText("Mã ngành");

        lblTenNganh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenNganh.setText("Tên ngành");

        lblMaKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaKhoa.setText("Mã khoa");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái hiển thị");

        cmbTrangThaiHienThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ẩn", "Hiển thị" }));
        cmbTrangThaiHienThi.setSelectedIndex(1);

        cmbMaKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "VT" }));

        javax.swing.GroupLayout pnlChiTietLayout = new javax.swing.GroupLayout(pnlChiTiet);
        pnlChiTiet.setLayout(pnlChiTietLayout);
        pnlChiTietLayout.setHorizontalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrangThai))
                .addGap(39, 39, 39)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTrangThaiHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pnlChiTietLayout.setVerticalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNganh))
                .addGap(18, 18, 18)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNganh))
                .addGap(18, 18, 18)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKhoa)
                    .addComponent(cmbMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai)
                    .addComponent(cmbTrangThaiHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pnlNutLenh.setBackground(new java.awt.Color(255, 255, 255));
        pnlNutLenh.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 10));

        btnThem.setBackground(new java.awt.Color(0, 102, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.setBorderPainted(false);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setPreferredSize(new java.awt.Dimension(80, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlNutLenh.add(btnThem);

        btnXoa.setBackground(new java.awt.Color(0, 102, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.setBorderPainted(false);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setMaximumSize(new java.awt.Dimension(44, 26));
        btnXoa.setMinimumSize(new java.awt.Dimension(44, 26));
        btnXoa.setPreferredSize(new java.awt.Dimension(80, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlNutLenh.add(btnXoa);

        btnSua.setBackground(new java.awt.Color(0, 102, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.setBorderPainted(false);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setMaximumSize(new java.awt.Dimension(44, 26));
        btnSua.setMinimumSize(new java.awt.Dimension(44, 26));
        btnSua.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlNutLenh.add(btnSua);

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLamMoi.setBorderPainted(false);
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.setMaximumSize(new java.awt.Dimension(44, 26));
        btnLamMoi.setMinimumSize(new java.awt.Dimension(44, 26));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(80, 30));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlNutLenh.add(btnLamMoi);

        btnXuat.setBackground(new java.awt.Color(0, 102, 255));
        btnXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnXuat.setText("Xuất danh sách");
        btnXuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXuat.setBorderPainted(false);
        btnXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuat.setMaximumSize(new java.awt.Dimension(44, 26));
        btnXuat.setMinimumSize(new java.awt.Dimension(44, 26));
        btnXuat.setPreferredSize(new java.awt.Dimension(120, 30));
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        pnlNutLenh.add(btnXuat);

        lblDanhSachKhoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDanhSachKhoa.setText("DANH SÁCH NGÀNH");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDanhSachKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDanhSachKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tblDSNganh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã ngành", "Tên ngành", "Mã khoa", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSNganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNganhMouseClicked(evt);
            }
        });
        scrDSNganh.setViewportView(tblDSNganh);

        javax.swing.GroupLayout pnlDSNganhLayout = new javax.swing.GroupLayout(pnlDSNganh);
        pnlDSNganh.setLayout(pnlDSNganhLayout);
        pnlDSNganhLayout.setHorizontalGroup(
            pnlDSNganhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrDSNganh)
        );
        pnlDSNganhLayout.setVerticalGroup(
            pnlDSNganhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSNganhLayout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrDSNganh, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDSNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNutLenh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNutLenh, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDSNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (txtMaNganh.getText().isEmpty()) {
                DialogHelper.showError("Mã ngành không được bỏ trống");
            } else if (txtMaNganh.getText().isEmpty()) {
                DialogHelper.showError("Tên ngành không được bỏ trống");
            } else if (NganhCtrl.kiemTraMaNganhDaTonTai(txtTenNganh.getText())) {
                DialogHelper.showError("Mã ngành đã tồn tại. Vui lòng nhập lại");
            } else if (cmbMaKhoa.getSelectedItem().toString().equals("---Mã khoa---")) {
                DialogHelper.showError("Mã khoa không được bỏ trống");
            } else {
                String maNganh = txtMaNganh.getText();
                String tenNganh = txtTenNganh.getText();
                String maKhoa = (String) cmbMaKhoa.getSelectedItem();
                int trangThai = cmbTrangThaiHienThi.getSelectedIndex();

                NganhModel nganh = new NganhModel(maNganh, maKhoa, tenNganh, trangThai);
                NganhCtrl.themNganh(nganh);
                DialogHelper.showMessage("Thêm ngành thành công!");
                hienThiDSNganh();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhoaCtrl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            if (txtMaNganh.getText().isEmpty()) {
                DialogHelper.showError("Vui lòng chọn ngành muốn chỉnh sửa");
            } else {
                if (txtMaNganh.getText().isEmpty()) {
                    DialogHelper.showError("Mã ngành không được bỏ trống");
                } else if (txtTenNganh.getText().isEmpty()) {
                    DialogHelper.showError("Tên ngành không được bỏ trống");
                } else if (cmbMaKhoa.getSelectedItem().toString().equals("---Mã khoa---")) {
                    DialogHelper.showError("Mã khoa không được bỏ trống");
                } else {
                    String maNganh = txtMaNganh.getText();
                    String tenNganh = txtTenNganh.getText();
                    String maKhoa = (String) cmbMaKhoa.getSelectedItem();
                    int trangThai = cmbTrangThaiHienThi.getSelectedIndex();

                    NganhModel nganh = new NganhModel(maNganh, maKhoa, tenNganh, trangThai);
                    NganhCtrl.capNhatNganh(nganh);
                    DialogHelper.showMessage("Cập nhật ngành thành công!");
                    lamMoi();
                    hienThiDSNganh();
                    txtMaNganh.setEnabled(true);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();
        hienThiDSNganh();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maNganh = txtMaNganh.getText();
        try {
            if (maNganh.isEmpty()) {
                DialogHelper.showError("Vui lòng chọn ngành muốn xóa");
            } else if (NganhCtrl.kiemTraNganhDaDuocSuDung(maNganh)) {
                DialogHelper.showError("Ngành đã có lớp không thể xóa!");
            } else {
                if (DialogHelper.showConfirmation("Bạn có chắc muốn xóa ngành này?")) {
                    try {
                        NganhCtrl.xoaNganh(maNganh);
                        hienThiDSNganh();
                        lamMoi();
                        DialogHelper.showMessage("Xóa ngành thành công");
                        txtMaNganh.setEnabled(true);
                    } catch (ClassNotFoundException | SQLException ex) {
                        Logger.getLogger(DSLop.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSNganh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDSNganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNganhMouseClicked
        txtMaNganh.setEnabled(false);
        int selectedIndex = tblDSNganh.getSelectedRow();
        if (selectedIndex >= 0) {
            NganhModel nganh = dsNganh.get(selectedIndex);

            txtMaNganh.setText(nganh.getMaNganh());
            txtTenNganh.setText(nganh.getTenNganh());
            cmbTrangThaiHienThi.setSelectedIndex(nganh.getTrangThaiHienThi());

            // Lấy mã khoa và set vào combobox MaKhoa
            String maKhoa = nganh.getMaKhoa();
            for (int i = 0; i < countMaKhoa; i++) {
                if (maKhoa.equals(dsMaKhoa.get(i))) {
                    cmbMaKhoa.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblDSNganhMouseClicked

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        NganhCtrl.xuatFileExcel(dsNganh, "src/main/java/files/DSNganh.xlsx");
        DialogHelper.showMessage("Xuất danh sách thành công!");
    }//GEN-LAST:event_btnXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSNganh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSNganh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSNganh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSNganh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSNganh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cmbMaKhoa;
    private javax.swing.JComboBox<String> cmbTrangThaiHienThi;
    private javax.swing.JLabel lblDanhSachKhoa;
    private javax.swing.JLabel lblMaKhoa;
    private javax.swing.JLabel lblMaNganh;
    private javax.swing.JLabel lblTenNganh;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JPanel pnlDSNganh;
    private javax.swing.JPanel pnlNutLenh;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JScrollPane scrDSNganh;
    private javax.swing.JTable tblDSNganh;
    private javax.swing.JTextField txtMaNganh;
    private javax.swing.JTextField txtTenNganh;
    // End of variables declaration//GEN-END:variables
}
